import type { Metadata } from 'next'
import { AlertTriangle, Lock, Globe, CheckCircle2, Zap, Eye, BookOpen } from 'lucide-react'
import NewsletterCTA from '@/components/NewsletterCTA'

export const metadata: Metadata = {
  title: 'Legal Risk Library — Solopreneur Legal Radar',
  description: 'AI risks, IP protection, platform vulnerabilities, cross-border legal issues, and a quarterly checklist for solopreneurs.',
}

export default function LegalRiskLibraryPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Hero */}
      <section className="relative overflow-hidden bg-gradient-to-br from-teal-600 to-teal-800 pt-16 pb-20 md:pt-24 md:pb-28">
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl">
            <div className="flex items-center gap-4 mb-6">
              <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center">
                <AlertTriangle className="w-6 h-6 text-white" />
              </div>
              <span className="text-sm font-semibold text-teal-100 uppercase tracking-wider">The Shield — Track 2</span>
            </div>
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-white mb-6">Legal Risk Library</h1>
            <p className="text-xl text-teal-100 leading-relaxed max-w-2xl">
              Four legal threats solopreneurs don't think about until they become critical: AI risks, unprotected IP, platform dependency, and cross-border complications. Here's how to see them coming.
            </p>
          </div>
        </div>
      </section>

      {/* Overview */}
      <section className="py-16 md:py-20 bg-gray-50 border-b border-gray-200">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-xl border border-gray-200 p-6 md:p-8 mb-8">
            <div className="flex gap-4">
              <AlertTriangle className="w-8 h-8 text-amber-600 shrink-0 mt-1" />
              <div>
                <p className="text-lg text-gray-900 mb-3">
                  <strong>Silent legal risks accumulate until they detonate.</strong>
                </p>
                <p className="text-gray-600">
                  Most solopreneurs operate without legal radar. You use AI tools without considering IP implications. You build on platforms you don't own. You serve clients internationally without understanding tax or contract law. These risks are invisible until a client disputes IP ownership, a platform API breaks your business, or you face unexpected cross-border tax liability.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Risk 1: AI-Driven Legal Risks */}
      <section className="py-16 md:py-20 border-b border-gray-100">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-start gap-4 mb-8">
            <Zap className="w-8 h-8 text-teal-600 shrink-0 mt-1" />
            <h2 className="text-2xl font-bold text-gray-900">Risk 1: AI-Driven Legal Exposure</h2>
          </div>

          <div className="space-y-6">
            <div className="bg-white rounded-xl border border-gray-100 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">The Problem</h3>
              <p className="text-gray-600 mb-4">
                You use ChatGPT to write content, generate images, analyze data, and build code. Most AI terms of service prohibit commercial use or claim partial ownership of outputs. You could unknowingly violate copyrights embedded in AI training data. You might sell a deliverable created by AI without clear IP ownership.
              </p>
              <ul className="space-y-3 text-sm text-gray-600 ml-4">
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> ChatGPT outputs: OpenAI claims no ownership, but users can sue each other over content disputes.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Image generators (Midjourney, Dall-E): Often prohibit commercial use unless you upgrade.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Code generated by AI: Risk of embedded copyrighted code from training data.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Client contracts: Do your T&Cs disclose AI use? Can clients compete based on AI-like work?</li>
              </ul>
            </div>

            <div className="bg-teal-50 rounded-xl border border-teal-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">Mitigation Checklist</h3>
              <ul className="space-y-3 text-sm text-gray-600">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Read the ToS: Know which AI tools allow commercial use. Document your compliance.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Disclose AI use: Tell clients if their deliverable was AI-assisted or AI-generated.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Modify outputs: AI generated content → refine, fact-check, add original analysis → reduces IP risk.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Use commercial plans: Upgrade to pro/commercial versions if you're using AI commercially.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Update contracts: Add clauses about AI use, IP ownership, and responsibilities.</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Risk 2: Intellectual Property */}
      <section className="py-16 md:py-20 border-b border-gray-100 bg-gray-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-start gap-4 mb-8">
            <Lock className="w-8 h-8 text-teal-600 shrink-0 mt-1" />
            <h2 className="text-2xl font-bold text-gray-900">Risk 2: Unprotected Intellectual Property</h2>
          </div>

          <div className="space-y-6">
            <div className="bg-white rounded-xl border border-gray-100 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">The Problem</h3>
              <p className="text-gray-600 mb-4">
                You build frameworks, templates, methodologies, or processes that differentiate your business. You rarely document them formally or copyright them. A client takes your methodology and uses it elsewhere. A competitor copies your service flow. You have no legal recourse because you never formalized IP ownership.
              </p>
              <ul className="space-y-3 text-sm text-gray-600 ml-4">
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Copyright: Automatically applied to original work (writing, code, designs), but prove it in disputes.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Trademarks: Your business name, tagline, or service name can be trademarked for £200–500.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Trade secrets: Undisclosed practices (like your proprietary process) need confidentiality agreements.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Patents: Expensive and slow; rare for solopreneurs unless you're tech-focused.</li>
              </ul>
            </div>

            <div className="bg-blue-50 rounded-xl border border-blue-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">IP Basics for Solopreneurs</h3>
              <div className="space-y-4 text-sm text-gray-600">
                <div>
                  <p className="font-semibold text-gray-900 mb-2">Copyright</p>
                  <p>Automatic on creation. Protects writing, code, designs. To strengthen: Add copyright notice (© 2024 Your Name), document creation date, register with UK IPO (£50).</p>
                </div>
                <div>
                  <p className="font-semibold text-gray-900 mb-2">Trademark</p>
                  <p>Protects your brand. Register your business name, tagline, or logo (£170 application fee). Search trademark.service.gov.uk first to avoid conflicts.</p>
                </div>
                <div>
                  <p className="font-semibold text-gray-900 mb-2">Confidentiality (NDA)</p>
                  <p>Use NDAs when sharing business secrets, frameworks, or client lists. Protects your competitive edge. Add to all client contracts.</p>
                </div>
                <div>
                  <p className="font-semibold text-gray-900 mb-2">Client IP Agreements</p>
                  <p>Clarify ownership: Do you retain methodology rights while client gets deliverable? Add explicit clause to every contract.</p>
                </div>
              </div>
            </div>

            <div className="bg-teal-50 rounded-xl border border-teal-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">Solopreneur IP Checklist</h3>
              <ul className="space-y-3 text-sm text-gray-600">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Document your IP: List all frameworks, templates, processes, brand assets you want to protect.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Add copyright notices: © 2024 [Your Name] on all original content and code.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Create a template NDA: Use when discussing sensitive business details with anyone.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Specify IP ownership in contracts: Make clear what you retain and what the client gets.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Consider trademark registration: Budget for business name/tagline if it's core to your brand (optional but recommended).</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Risk 3: Platform Dependency */}
      <section className="py-16 md:py-20 border-b border-gray-100">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-start gap-4 mb-8">
            <Globe className="w-8 h-8 text-teal-600 shrink-0 mt-1" />
            <h2 className="text-2xl font-bold text-gray-900">Risk 3: Platform Dependency & Vulnerability</h2>
          </div>

          <div className="space-y-6">
            <div className="bg-white rounded-xl border border-gray-100 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">The Problem</h3>
              <p className="text-gray-600 mb-4">
                You rely on platforms you don't control: email marketing (Mailchimp), payment processors (Stripe), scheduling (Calendly), or project management (Asana). If the platform changes terms, raises prices, gets hacked, or discontinues service, your business is at risk. You own no customer data. You can't easily switch.
              </p>
              <ul className="space-y-3 text-sm text-gray-600 ml-4">
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> API deprecation: Platforms change or discontinue APIs. Your integrations break overnight.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Account suspension: TOS violation (real or mistaken) and your account freezes.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Price increases: Your platform doubles fees; you have no alternative without replatforming.</li>
                <li className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> Data lock-in: You can't export customer data easily. You're trapped.</li>
              </ul>
            </div>

            <div className="bg-teal-50 rounded-xl border border-teal-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">Mitigation Checklist</h3>
              <ul className="space-y-3 text-sm text-gray-600">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Audit your platforms: List every SaaS tool you depend on. Which are business-critical?</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Identify lock-in points: Which platforms hold your customer data? Can you export it?</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Know alternatives: For each critical tool, identify 2–3 alternatives you could switch to.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Regular backups: Download your data quarterly from key platforms (especially email lists).</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Diversify platforms: Don't use only Stripe for payments or only AWS for hosting. Have a backup.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Read ToS changes: Most platforms notify users of changes. Don't ignore them.</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Risk 4: Cross-Border Legal */}
      <section className="py-16 md:py-20 border-b border-gray-100 bg-gray-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-start gap-4 mb-8">
            <Eye className="w-8 h-8 text-teal-600 shrink-0 mt-1" />
            <h2 className="text-2xl font-bold text-gray-900">Risk 4: Cross-Border Legal Complications</h2>
          </div>

          <div className="space-y-6">
            <div className="bg-white rounded-xl border border-gray-100 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">The Problem</h3>
              <p className="text-gray-600 mb-4">
                You work with clients in different countries. You're unclear on tax obligations, contract law, data protection (GDPR), and liability. Different jurisdictions have different rules. You might unknowingly breach privacy laws, owe international taxes, or face liability for cross-border violations.
              </p>
            </div>

            <div className="bg-blue-50 rounded-xl border border-blue-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">Key Cross-Border Issues</h3>
              <div className="space-y-4 text-sm text-gray-600">
                <div>
                  <p className="font-semibold text-gray-900 mb-2">Tax (IMPORTANT)</p>
                  <p>If you serve UK clients and work remotely for foreign clients, understand IR35 (IR35 legislation affects contractor taxation). Serve EU clients? You might owe VAT or income tax on foreign earnings. Consult your accountant about international tax obligations.</p>
                </div>
                <div>
                  <p className="font-semibold text-gray-900 mb-2">GDPR (EU + UK)</p>
                  <p>If you store personal data of EU/UK residents (client names, emails, etc.), GDPR applies. You need a privacy policy, data protection agreement, and secure data handling. Non-compliance: fines up to €20M or 4% of revenue.</p>
                </div>
                <div>
                  <p className="font-semibold text-gray-900 mb-2">Contract Law</p>
                  <p>Different countries have different contract enforcement rules. Your UK contract might not be enforceable in the US. Specify which law governs the contract (usually the place you're based).</p>
                </div>
                <div>
                  <p className="font-semibold text-gray-900 mb-2">Payment Currency and Disputes</p>
                  <p>Multi-currency payments add FX risk and complexity. Specify payment terms, currency, and dispute resolution (arbitration vs. legal action).</p>
                </div>
              </div>
            </div>

            <div className="bg-teal-50 rounded-xl border border-teal-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">International Client Checklist</h3>
              <ul className="space-y-3 text-sm text-gray-600">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Ask your accountant: What international tax obligations do you have?</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Create a privacy policy: If you store ANY client/user data, add a privacy policy to your website.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Add contract clause: Specify which country's law governs the contract (usually yours).</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Document payments: Keep records of currency, FX rates, and amounts paid (for tax reporting).</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Use payment processors: Stripe, Wise, or PayPal handle some compliance automatically.</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Quarterly Legal Radar */}
      <section className="py-16 md:py-20 border-b border-gray-100">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-start gap-4 mb-8">
            <BookOpen className="w-8 h-8 text-teal-600 shrink-0 mt-1" />
            <h2 className="text-2xl font-bold text-gray-900">Quarterly Legal Radar Checklist</h2>
          </div>

          <p className="text-gray-600 mb-8">Run this checklist every 3 months. Takes 30 minutes. Updates you on emerging legal risks.</p>

          <div className="space-y-6">
            {/* Q1 */}
            <div className="bg-white rounded-xl border border-gray-100 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">Once per Quarter (all quarters)</h3>
              <ul className="space-y-3 text-sm text-gray-600 ml-4">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Review all active client contracts. Any changes to scope, timeline, or disputes?</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Check IP protection: Have you documented new frameworks or methodologies? Any new trademarks to register?</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Review SaaS platforms: Any price increases, ToS changes, or deprecations announced?</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Backup critical data: Download customer lists, contracts, and business records from platforms.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Review AI tool usage: Are you still compliant with ToS? Any new risks?</li>
              </ul>
            </div>

            {/* January (Q1) */}
            <div className="bg-amber-50 rounded-xl border border-amber-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">January (End of Quarter 4 / Annual Review)</h3>
              <ul className="space-y-3 text-sm text-gray-600 ml-4">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Annual tax review: Meet with accountant. Understand international tax changes (Brexit, new rates, etc.).</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Update privacy policy: Review GDPR/data protection laws. Update your website privacy policy.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Contract templates: Are your standard contract templates still relevant? Any clauses to add/remove?</li>
              </ul>
            </div>

            {/* April (Q2) */}
            <div className="bg-blue-50 rounded-xl border border-blue-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">April (Mid-Year Review)</h3>
              <ul className="space-y-3 text-sm text-gray-600 ml-4">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Platform audit: Any new SaaS tools you're depending on? Add to your backup schedule.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Competitor check: Are competitors using your IP/methodology? Consider cease-and-desist if needed.</li>
              </ul>
            </div>

            {/* July (Q3) */}
            <div className="bg-indigo-50 rounded-xl border border-indigo-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">July (Industry Check)</h3>
              <ul className="space-y-3 text-sm text-gray-600 ml-4">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Industry regulation updates: Any new legal requirements in your industry?</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> AI tools: New policies on commercial use, data training, or liability?</li>
              </ul>
            </div>

            {/* October (Q4) */}
            <div className="bg-violet-50 rounded-xl border border-violet-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">October (Preparation for Year End)</h3>
              <ul className="space-y-3 text-sm text-gray-600 ml-4">
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Year-end tax prep: Gather all invoices, expenses, and international payment records for accountant.</li>
                <li className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" /> Contract compliance: Issue reminders to clients with upcoming contract renewals (within 90 days).</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Key Takeaway */}
      <section className="py-16 md:py-20 bg-teal-50 border-t border-teal-200">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-xl border-2 border-teal-200 p-8">
            <p className="text-lg text-gray-900 mb-4"><strong>Legal protection is about visibility and preparation:</strong></p>
            <p className="text-gray-600">You can't eliminate legal risk, but you can see it coming. Run the quarterly radar. Understand your platform dependencies. Clarify IP ownership in contracts. Know your international obligations. Most legal problems start small and grow. Early visibility lets you act before they become crises.</p>
          </div>
        </div>
      </section>

      <NewsletterCTA />
    </div>
  )
}
